

inhibit_all_warnings!
platform :ios, '9.0'


flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ticketOrderDemo' do

   # Pods for ticketOrderDemo
   install_all_flutter_pods(flutter_application_path)

end